# Generated by Django 5.2.7 on 2025-10-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork_lesson_40', '0003_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('settlement', models.ManyToManyField(to='classwork_lesson_40.settlement')),
            ],
        ),
    ]
